apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper-pod
spec:
  containers:
  - env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181" 
    - name: ZOOKEEPER_TICK_TIME
      value: "2000" 
    image: confluentinc/cp-zookeeper:7.2.1
    name: zookeeper-pod
