apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka-pod
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpwd  
    - name: MYSQL_MULTIPLE_DATABASES
      value: lecture,member
    - name: MYSQL_USER
      value: user
    - name: MYSQL_PASSWORD
      value: pwd
    image: mysql:5.7
    name: mysql-pod
    ports:
    - containerPort: 3306
    resources: {}
    
    
    

    volumes:
      - ./initialize_mysql_multiple_databases.sh:/docker-entrypoint-initdb.d/initialize_mysql_multiple_databases.sh
      - mysql-volume:/var/lib/mysql
    command:  #한글관련 추가
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10    