version: '2'

services:
  category:
    build: lecturecategory-domain
    mem_limit: 600m
    mem_reservation: 512m
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  member:
    build: member-domain
    mem_limit: 600m
    mem_reservation: 512m
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  auction:
    build: auction-domain
    mem_limit: 600m
    mem_reservation: 512m
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#  lecture:
#    build: lecture-domain
#    mem_limit: 550M
#    ports:
#      - "8000:8000"
#      - "8081:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - my-kafka
#      - mysql
#      - gateway

