version: '2'

services:

  lecture:
#    build: lecture
    image: jcscom13/lecture-domain-docker:latest

    mem_limit: 512m
    ports:
      - 8000:8000
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - kafka