version: '2'

services:
  lecture:
    build: lecture-domain
    mem_limit: 550M
    ports:
      - "8000:8000"
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - my-kafka
#      - mysql
#      - gateway
