version: '2'
services:
#gateway설정: 8080에서 각각의 docker엔진으로 라우팅 설정 추가
# 일단은 Member, lecture, category만 추가
  gateway:
    build: gateway
    mem_limit: 200m
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker


