version: '2'
volumes:
  mysql-volume: {}
services:
  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_MULTIPLE_DATABASES=lecture,member
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./initialize_mysql_multiple_databases.sh:/docker-entrypoint-initdb.d/initialize_mysql_multiple_databases.sh
      - mysql-volume:/var/lib/mysql
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10    