server:
  port: 8082
server.servlet.context-path: /category

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
#        event-in:
#          group: lecturecategory
#          destination: lecture
#          contentType: application/json
        out-categoryChanged:  #producer의 이벤트 이름
          destination: categoryChanged  #토픽이름
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
#       event-in:
#         group: lecturecategory
#         destination: lecture
#         contentType: application/json
        out-categoryChanged:  #producer의 이벤트 이름
          destination: categoryChanged  #토픽이름
          contentType: application/json
