server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    config.import-check.enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
      discovery:
        locator:
          enabled: true
      routes:
        - id: signup
          uri: http://localhost:8080
          predicates:
            - Path=/signup
            - Method=POST
        - id: login
          uri: http://localhost:8080
          predicates:
            - Path=/login
            - Method=POST
        - id: member
          uri: http://localhost:8080
          predicates:
            - Path=/members**
            - Method=POST,GET,PUT,OPTIONS,DELETE
          filters:
            - AuthorizationHeaderFilter
        - id: member-admin
          uri: http://localhost:8080
          predicates:
            - Path=/admin/members**
            - Method=POST,GET,PUT,OPTIONS,DELETE
          filters:
            - AuthorizationHeaderFilter
        - id: lecture
          uri: http://localhost:8081
          predicates:
            - Path=/lecture/**
        - id: lecture-category
          uri: http://localhost:8082
          predicates:
            - Path=/lectureCategories/**
          filters:
            - AuthorizationHeaderFilter
        - id: interest-category
          uri: http://localhost:8082
          predicates:
            - Path=/interestCategories/**
          filters:
            - AuthorizationHeaderFilter
        - id: auctions
          uri: http://localhost:8084
          predicates:
            - Path=/auctions/**
          filters:
            - AuthorizationHeaderFilter
        - id: lectureBids
          uri: http://localhost:8084
          predicates:
            - Path=/lectureBids/**
          filters:
            - AuthorizationHeaderFilter
        - id: lectureRegisters
          uri: http://localhost:8083
          predicates:
            - Path=/lectureRegisters/**
          filters:
            - AuthorizationHeaderFilter
        - id: default
          uri: http://localhost:8080
          predicates:
            - Path=/**

token:
  secret: amf42_token
---
spring:
  profiles: docker
  cloud:
    config.import-check.enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: signup
          uri: http://member:8080
          predicates:
            - Path=/signup
            - Method=POST
        - id: login
          uri: http://member:8080
          predicates:
            - Path=/login
            - Method=POST
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members**
            - Method=POST,GET,PUT,OPTIONS,DELETE
          filters:
            - AuthorizationHeaderFilter
        - id: member-admin
          uri: http://member:8080
          predicates:
            - Path=/admin/members**
            - Method=POST,GET,PUT,OPTIONS,DELETE
          filters:
            - AuthorizationHeaderFilter
        - id: lecture
          uri: http://lecture:8080
          predicates:
            - Path=/lecture/**
        - id: category
          uri: http://category:8080
          predicates:
            - Path=/category/**
        - id: lecture-category
          uri: http://category:8080
          predicates:
            - Path=/lectureCategories/**
          filters:
            - AuthorizationHeaderFilter
        - id: interest-category
          uri: http://category:8080
          predicates:
            - Path=/interestCategories/**
          filters:
            - AuthorizationHeaderFilter
        - id: auctions
          uri: http://auction:8080
          predicates:
            - Path=/auctions/**
          filters:
            - AuthorizationHeaderFilter
        - id: lectureBids
          uri: http://auction:8080
          predicates:
            - Path=/lectureBids/**
          filters:
            - AuthorizationHeaderFilter
        - id: lectureRegisters
          uri: http://localhost:8080
          predicates:
            - Path=/lectureRegisters/**
          filters:
            - AuthorizationHeaderFilter
        - id: default
          uri: http://member:8080
          predicates:
            - Path=/**
server:
  port: 8080
token:
  secret: amf42_token
