server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    config.import-check.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: member
          uri: http://localhost:8082
          predicates:
            - Path=/member/**
        - id: lecture
          uri: http://localhost:8081
          predicates:
            - Path=/lecture/**
        - id: pet-front
          uri: http://localhost:8084
          predicates:
            - Path=/**
---

spring:
  profiles: docker
  cloud:
    config.import-check.enabled: false
    gateway:
      discovery:
        locator:
          enabled: false

spring.cloud.gateway.routes:
- id: category
  uri: http://category:8080
  predicates:
  - Path=/category/**
- id: member
  uri: http://member:8080
  predicates:
  - Path=/member/**
- id: lecture
  uri: http://lecture:8080
  predicates:
  - Path=/lecture/**

server.port: 8080
