server.servlet.context-path: /lecture

---
server.port: 8081

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: lecture
          destination: lecture-category
          contentType: application/json
        event-out:
          destination: lecture-category
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


---

spring.profiles: docker

server.port: 8080

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: lecture
          destination: lecture-category
          contentType: application/json
        event-out:
          destination: lecture-category
          contentType: application/json

spring.datasource:
  url: jdbc:mysql://mysql/lecture
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000  

spring.jpa.generate-ddl: true 
spring.jpa.hibernate.ddl-auto: update 
spring.jpa.properties:
  hibernate:
    show_sql: true
    format_sql: true
