server:
  port: 8084

#spring.mvc.pathmatch.matching-strategy: ant_path_matcher

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      default-binder: kafka
      kafka:
         binder:
           brokers: everyonelecture.servicebus.windows.net:9093

      bindings:
        event-in:
          destination: lecture_local
          group: amf42_local
          contentType: application/json
        event-out:
          destination: lecture_local
          contentType: application/json

      function:
        definition: consume;supply;
      poller:
        initial-delay: 0
        fixed-delay: 1000
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
---
spring.profiles: docker

spring.jpa.generate-ddl: true 
spring.jpa.hibernate.ddl-auto: update 

spring.jpa.properties:
  hibernate:
    show_sql: true
    format_sql: true
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        event-in:
          destination: lecture
          group: amf42_local
          contentType: application/json
        event-out:
          destination: lecture_local
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

