server.servlet.context-path: /member
server.port: 8080

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #       dialect: org.hibernate.dialect.MySQL57Dialect
  # datasource:
  #   url: jdbc:mysql://localhost:3306/petstore
  #   username: root
  #   password: admin
  #   driverClassName: com.mysql.cj.jdbc.Driver


spring.datasource:
  url: jdbc:mysql://mysql/member
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

spring.jpa.generate-ddl: true
