apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: .\kompose convert -f docker-compose-infra.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: .\kompose convert -f docker-compose-infra.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci
            - --ignore-db-dir=lost+found
          env:
            - name: MYSQL_MULTIPLE_DATABASES
              value: lecture,member
            - name: MYSQL_PASSWORD
              value: pwd
            - name: MYSQL_ROOT_PASSWORD
              value: rootpwd
            - name: MYSQL_USER
              value: user
          image: acr13myinno.azurecr.io/myinno-mysql:5.7
          name: mysql
#          command: ["sh", "-c", "echo 'sleep 60000'"]
#debug을 위하여
#        imagePullPolicy: Always      
#          command: [--ignore-db-dir=lost+found]
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: "314572800"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: kompose-mysql-volume
      restartPolicy: Always
      volumes:
        - name: kompose-mysql-volume
          persistentVolumeClaim:
            claimName: kompose-mysql-volume
status: {} 

---
#Mysql Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: .\kompose convert -f docker-compose-infra.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql

spec:
  type: LoadBalancer
  ports:
    - name: "mysql-service-port"
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
#    io.kompose.service: mysql
status:
  loadBalancer: {}
---
#볼륨 생성
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kompose-mysql-volume
  name: kompose-mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}


