apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
#      nodeSelector:
#        "beta.kubernetes.io/os": linux      
      containers:
      - name: member
        image: acr13myinno.azurecr.io/member
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "576716800"
        env:
        - name: JVM_OPTS
          value: -Xmx400m -Xms400m -XX:MaxPermSize=128m
        - name: SPRING_PROFILES_ACTIVE
          value: docker
      restartPolicy: Always          
---

apiVersion: v1
kind: Service
metadata:
  name: member

spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: member
